services:
  nginx-proxy:
    image: docker.io/nginx:stable-alpine
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: ${INSTANCE_PREFIX:-mycloud}_nginx_proxy
    restart: always
    ports:
      - "${IP:-0.0.0.0}:${DOCKER_HTTP:-80}:80"
      - "${IP:-0.0.0.0}:${DOCKER_HTTPS:-443}:443"
    volumes:
      - ${NGINX_PROXY_PATH:-./nginx-proxy}/conf.d:/etc/nginx/conf.d
      - ${NGINX_PROXY_PATH:-./nginx-proxy}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_PROXY_PATH:-./nginx-proxy}/html:/usr/share/nginx/html
      - ${NGINX_PROXY_PATH:-./nginx-proxy}/certs:/etc/nginx/certs:ro
    logging:
      driver: ${NGINX_PROXY_LOG_DRIVER:-json-file}
      options:
        max-size: ${NGINX_PROXY_LOG_MAX_SIZE:-4m}
        max-file: ${NGINX_PROXY_LOG_MAX_FILE:-10}
    networks:
      - proxy-network
  
  docker-gen:
    image: docker.io/aveferrum/docker-gen:latest
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen: "true"
    command: -notify-sighup ${INSTANCE_PREFIX:-mycloud}_nginx_proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: ${INSTANCE_PREFIX:-mycloud}_docker_gen
    restart: always
    environment:
      SSL_POLICY: ${SSL_POLICY:-Mozilla-Intermediate}
    volumes:
      - ${NGINX_PROXY_PATH:-./nginx-proxy}/conf.d:/etc/nginx/conf.d
      - ${NGINX_PROXY_PATH:-./nginx-proxy}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_PROXY_PATH:-./nginx-proxy}/html:/usr/share/nginx/html
      - ${NGINX_PROXY_PATH:-./nginx-proxy}/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    logging:
      driver: ${DOCKER_GEN_LOG_DRIVER:-json-file}
      options:
        max-size: ${DOCKER_GEN_LOG_MAX_SIZE:-2m}
        max-file: ${DOCKER_GEN_LOG_MAX_FILE:-10}
    networks:
      - proxy-network
    
  acme-companion:
    image: docker.io/aveferrum/acme-companion:latest
    container_name: ${INSTANCE_PREFIX:-mycloud}_acme_companion
    restart: always
    volumes:
      - ${NGINX_PROXY_PATH:-./nginx-proxy}/conf.d:/etc/nginx/conf.d
      - ${NGINX_PROXY_PATH:-./nginx-proxy}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_PROXY_PATH:-./nginx-proxy}/html:/usr/share/nginx/html
      - ${NGINX_PROXY_PATH:-./nginx-proxy}/certs:/etc/nginx/certs:rw
      - ${NGINX_PROXY_PATH:-./nginx-proxy}/acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: ${INSTANCE_PREFIX:-mycloud}_docker_gen
      NGINX_PROXY_CONTAINER: ${INSTANCE_PREFIX:-mycloud}_nginx_proxy
    logging:
      driver: ${ACME_COMPANION_LOG_DRIVER:-json-file}
      options:
        max-size: ${ACME_COMPANION_LOG_MAX_SIZE:-2m}
        max-file: ${ACME_COMPANION_LOG_MAX_FILE:-10}
    networks:
      - proxy-network
    
  nextcloud-database:
    image: docker.io/postgres:13-alpine
    container_name: ${INSTANCE_PREFIX:-mycloud}_database
    restart: always
    volumes:
      - ${NEXTCLOUD_PATH:-./nextcloud}/db:/var/lib/postgresql/data
    env_file:
      - ./env-files/nextcloud-database.env
    networks:
      - nextcloud-network

  nextcloud-app:
    image: docker.io/nextcloud:fpm-alpine
    container_name: ${INSTANCE_PREFIX:-mycloud}_app
    restart: always
    volumes: 
      - ${NEXTCLOUD_PATH:-./nextcloud}/data:/var/www/html
    env_file:
      - ./env-files/nextcloud-app.env
    environment:
      - POSTGRES_HOST=${INSTANCE_PREFIX:-mycloud}_database
    depends_on:
      - nextcloud-database
    networks:
      - nextcloud-network

  nextcloud-web:
    image: docker.io/nginx:alpine
    container_name: ${INSTANCE_PREFIX:-mycloud}_web
    restart: always
    expose:
      - "80"
    depends_on:
      - nginx-proxy
      - docker-gen
      - acme-companion
    volumes:
      - ${NEXTCLOUD_PATH:-./nextcloud}/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${NEXTCLOUD_PATH:-./nextcloud}/data:/var/www/html:ro
    env_file:
      - ./env-files/nextcloud-web.env
    networks:
      - proxy-network
      - nextcloud-network

networks:
  proxy-network:
    external: true
    name: ${INSTANCE_PREFIX:-mycloud}-proxy-network
  nextcloud-network:
    external: true
    name: ${INSTANCE_PREFIX:-mycloud}-nextcloud-network
